//incrase dan dercrease
#include <iostream.h>
#include <conio.h>
main()
{
   int il=4,i2=4;
   int jl=8,j2=8;
   int a,b,c,d;
   a=++il;
   b=i2++;
   c=--jl;
   d=j2--;
   cout<<"\nNilai a = "<<a;
   cout<<"\nNilai il = "<<il;
   cout<<"\n\nNilai b = "<<b;
   cout<<"\nNilai i2 = "<<i2;
   cout<<"\n\nNilai c = "<<c;
   cout<<"\nNilai jl = "<<jl;
   cout<<"\n\nilai d = "<<d;
   cout<<"\nNilai j2 = "<<j2;
   getch ();}
